// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPbHcT5j3lLVMDAmDX5IAHJuk98vpCH_s',
    appId: '1:90435088180:web:09b269403a57c16dda7f61',
    messagingSenderId: '90435088180',
    projectId: 'aqua-sense-7d9d4',
    authDomain: 'aqua-sense-7d9d4.firebaseapp.com',
    storageBucket: 'aqua-sense-7d9d4.firebasestorage.app',
    measurementId: 'G-405T9QWW38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdgMQTIGRNFcmvszxyQbG-H4GCcRY58yc',
    appId: '1:90435088180:android:9c8e3d80bee7208fda7f61',
    messagingSenderId: '90435088180',
    projectId: 'aqua-sense-7d9d4',
    storageBucket: 'aqua-sense-7d9d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUJP9s461ZfWhb6LnCHvXgVVFzYF9QynU',
    appId: '1:90435088180:ios:ef1253cb11927170da7f61',
    messagingSenderId: '90435088180',
    projectId: 'aqua-sense-7d9d4',
    storageBucket: 'aqua-sense-7d9d4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUJP9s461ZfWhb6LnCHvXgVVFzYF9QynU',
    appId: '1:90435088180:ios:ef1253cb11927170da7f61',
    messagingSenderId: '90435088180',
    projectId: 'aqua-sense-7d9d4',
    storageBucket: 'aqua-sense-7d9d4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPbHcT5j3lLVMDAmDX5IAHJuk98vpCH_s',
    appId: '1:90435088180:web:c65db1bfc0630f6eda7f61',
    messagingSenderId: '90435088180',
    projectId: 'aqua-sense-7d9d4',
    authDomain: 'aqua-sense-7d9d4.firebaseapp.com',
    storageBucket: 'aqua-sense-7d9d4.firebasestorage.app',
    measurementId: 'G-PLMNWYYMM6',
  );

}