import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generateReport = (sensorData, alerts) => {
    const doc = new jsPDF();

    // Color Palette
    const primaryColor = [14, 165, 233]; // Sky 500

    // Header
    doc.setFillColor(...primaryColor);
    doc.rect(0, 0, 210, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.text("AquaSense", 14, 20);
    doc.setFontSize(12);
    doc.text("Intelligent Water Leak Detection System", 14, 28);
    doc.text(`Date: ${new Date().toLocaleString()}`, 140, 28);

    // Summary Section
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.text("System Summary", 14, 55);
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    let systemStatus = "Normal";
    if (alerts.some(a => a.type === 'Leak Detected')) systemStatus = "LEAK DETECTED";
    else if (alerts.some(a => a.type === 'Vibration Alarm')) systemStatus = "VIBRATION ALARM";

    doc.text([
        `Report Generated By: Admin User`,
        `Total Alerts Recorded: ${alerts.length}`,
        `System Status: ${systemStatus}`,
        `Sensor Health: Good`
    ], 14, 62);

    // Sensor Statistics Table
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.text("Recent Sensor Readings", 14, 90);

    const tableData = sensorData.slice(0, 15).map(reading => [
        new Date(reading.timestamp).toLocaleTimeString(),
        `${reading.flowRate?.toFixed(1) || 0} L/min`,
        `${reading.totalUsage?.toFixed(1) || 0} L`,
        `${reading.pressure?.toFixed(1) || 0} PSI`,
        `${reading.vibration?.toFixed(3) || 0} g`,
        reading.leakStatus === 1 ? "LEAK" : "OK"
    ]);

    autoTable(doc, {
        startY: 95,
        head: [['Time', 'Flow Rate', 'Total Usage', 'Pressure', 'Vibration', 'Status']],
        body: tableData,
        theme: 'grid',
        headStyles: { fillColor: primaryColor, textColor: 255 },
        alternateRowStyles: { fillColor: [240, 249, 255] }
    });

    // Alerts Section
    const finalY = doc.lastAutoTable.finalY + 15;
    doc.text("Alert Log", 14, finalY);

    const alertData = alerts.slice(0, 20).map(alert => [
        new Date(alert.timestamp).toLocaleTimeString(),
        alert.type,
        alert.formatted || alert.message,
        "Logged"
    ]);

    autoTable(doc, {
        startY: finalY + 5,
        head: [['Time', 'Type', 'Message', 'Status']],
        body: alertData,
        theme: 'striped',
        headStyles: { fillColor: [239, 68, 68], textColor: 255 }
    });

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("AquaSense Final Year Project Report - Confidential", 14, 290);

    doc.save(`AquaSense_Report_${new Date().toISOString().split('T')[0]}.pdf`);
};

export const generateTotalSummary = (alerts, thresholds) => {
    const doc = new jsPDF();
    const primaryColor = [79, 70, 229]; // Indigo 600

    // Header
    doc.setFillColor(...primaryColor);
    doc.rect(0, 0, 210, 50, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.text("AquaSense Executive Summary", 14, 25);
    doc.setFontSize(10);
    doc.text(`System Configuration: Flow > ${thresholds?.flowLimit}L/min | Duration > ${thresholds?.leakDuration}min`, 14, 35);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 140, 35);

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.text("Global System Health Metrics", 14, 70);

    const leakAlerts = alerts.filter(a => a.type === 'Leak Detected');
    const vibAlerts = alerts.filter(a => a.type === 'Vibration Alarm');
    const resolved = alerts.filter(a => a.maintenanceStatus === 'resolved').length;
    const pending = alerts.filter(a => a.maintenanceStatus === 'pending' || !a.maintenanceStatus).length;

    const summaryStats = [
        ["Metric", "Value", "Status"],
        ["Total Anomalies Detected", alerts.length, "Review Required"],
        ["Confirmed Leaks", leakAlerts.length, leakAlerts.length > 0 ? "Critical" : "Optimal"],
        ["Vibration Events", vibAlerts.length, "Monitor"],
        ["Maintenance: Resolved", resolved, "Healthy"],
        ["Maintenance: Pending", pending, pending > 5 ? "Action Needed" : "Manageable"]
    ];

    autoTable(doc, {
        startY: 75,
        head: [summaryStats[0]],
        body: summaryStats.slice(1),
        theme: 'grid',
        headStyles: { fillColor: primaryColor }
    });

    const finalY = doc.lastAutoTable.finalY + 20;
    doc.setFontSize(14);
    doc.text("Maintenance Backlog (Pending)", 14, finalY);

    const backlogData = alerts
        .filter(a => a.maintenanceStatus === 'pending' || !a.maintenanceStatus)
        .slice(0, 25)
        .map(a => [
            new Date(a.timestamp).toLocaleDateString(),
            a.type,
            a.message
        ]);

    autoTable(doc, {
        startY: finalY + 5,
        head: [['Date', 'Anomaly Type', 'Description']],
        body: backlogData,
        theme: 'striped',
        columnStyles: { 2: { cellWidth: 100 } }
    });

    return doc;
};
